#GET http://localhost:3000/ HTTP/1.1
###########
GET http://localhost:3000/alunos HTTP/1.1
#########
GET http://localhost:3000/alunos/filtro?email=hiallyrabelo@gmail.com HTTP/1.1
######### HTTP/1.1
#########
DELETE http://localhost:3000/alunos/5de6de620b6ffd144c7c09bb HTTP/1.1
##########################
PUT  /alunos/5de8d4713e4ee0267488a24e HTTP/1.1
Host : localhost:3000
content-type: application/json

{
    "nome" : "Paulo Guedes",
    "email" : "paulog@ifb"
}

###################

POST /alunos HTTP/1.1
Host: localhost:3000
content-type: application/json

{
    "nome" : "Pedro",
    "email" : "p@ifb"
}